Add support for arm64 architecture
snapcrafters/eclipse pull request #48
Opened 2022-12-08 19:14 UTC by ThyMYthOS

2023-07-24 10:01 UTC, Mailaender commented on snap/snapcraft.yaml
> +      - to arm64: "https://download.eclipse.org/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-aarch64.tar.gz"
```suggestion
      - on amd64: "https://download.eclipse.org/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz"
      - on arm64: "https://download.eclipse.org/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-aarch64.tar.gz"
```
?

2023-10-08 18:51 UTC, merlijn-sebrechts commented
This fails to build and has conflicts with the main branch. @ThyMYthOS do you want to continue working on it, or should we close this PR?

2023-10-08 18:51 UTC, merlijn-sebrechts requested changes, later dismissed
This fails to build and has conflicts with the main branch. @ThyMYthOS do you want to continue working on it, or should we close this PR?

2023-10-13 07:44 UTC, ThyMYthOS commented
The version is outdated anyway. I will give it another try using your suggestions.

2023-10-17 14:00 UTC, ThyMYthOS commented
@merlijn-sebrechts seems that `source-checksum` does not support advanced grammar. Any idea how to solve this?

2023-10-18 19:11 UTC, merlijn-sebrechts commented
It seems like it's building on X86_64!

Have you tested this on `arm` yourself? If you don't have an arm device, you can use remote-build to build on the launchpad builders from your local machine: https://snapcraft.io/docs/remote-build

Alternatively, you could modify the GitHub action to also build on arm, like we do for gimp: https://github.com/snapcrafters/gimp/blob/master/.github/workflows/build-prs.yml

How do you want to proceed?

2023-12-15 17:22 UTC, jnsgruk approved these changes
I just built this locally for amd64, and also tested `remote-buiild` for `arm64` and it's all good! I'll merge this and follow up another time with a CI uplift to follow the latest actions. Thanks!

2023-12-15 17:35 UTC, merged